import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

/*
  15 toffee 15 hi wrapper 
  3 wrapper dene par ek toffe milti hai
  total kitni toffe khayi
*/ 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <header
          style={{
            background: 'lightblue',
            padding: '15px'
          }}
        >
          <Link href={'./'}>go back</Link>
        </header>
        {children}
        <footer
          style={{
            background: 'lightblue',
            padding: '15px'
          }}
        >footer</footer>
      </body>
    </html>
  )
}